name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: bashmgmt/.github/.github/workflows/rust-ci.yml@main
    with:
      test: |
        cargo test
      bash-versions: '["system", "5.3.9"]'
